# Generated by Django 4.2.7 on 2023-11-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0009_cursos_abe'),
        ('convivencia', '0009_auto_20190127_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amonestaciones',
            name='IdAlumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.alumnos'),
        ),
        migrations.AlterField(
            model_name='amonestaciones',
            name='Profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.profesores'),
        ),
        migrations.AlterField(
            model_name='sanciones',
            name='IdAlumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.alumnos'),
        ),
    ]
