# Generated by Django 4.2.7 on 2023-11-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convivencia', '0010_alter_amonestaciones_idalumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amonestaciones',
            name='Enviado',
            field=models.BooleanField(default=False, verbose_name='Enviado por correo electrónico'),
        ),
    ]
