# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0006_auto_20161106_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
