# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2021-11-08 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0007_alumnos_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesores',
            options={'ordering': ('Apellidos',), 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
