# Generated by Django 4.2.7 on 2023-11-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0008_auto_20211108_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='Abe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
