# Generated by Django 4.2.7 on 2023-11-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0009_cursos_abe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='Bil',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='Ce',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='Etcp',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='Tic',
        ),
    ]
