# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2021-11-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro', '0008_auto_20211108_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('NroFaltas', models.IntegerField(default=0)),
                ('Notificada', models.BooleanField()),
                ('Medio', models.CharField(choices=[('1', 'Tel\xe9fono'), ('2', 'Correo ordinario'), ('3', 'Correo certificado')], default='1', max_length=1)),
                ('Comentario', models.TextField(blank=True)),
                ('IdAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centro.Alumnos')),
            ],
            options={
                'verbose_name': 'Actuaci\xf3n',
                'verbose_name_plural': 'Actuaciones',
            },
        ),
        migrations.CreateModel(
            name='TiposActuaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoActuacion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Tipo Actuaci\xf3n',
                'verbose_name_plural': 'Tipos de Actuaci\xf3n',
            },
        ),
        migrations.AddField(
            model_name='actuaciones',
            name='Tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tipo_de', to='absentismo.TiposActuaciones'),
        ),
    ]
