# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Idc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.ClaseDocumento'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Idp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Procedencia'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Idr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Remitente'),
        ),
    ]
