# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20161031_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remitente',
            options={'verbose_name': 'Remitente', 'verbose_name_plural': 'Remitentes'},
        ),
    ]
