# Generated by Django 4.2.7 on 2023-11-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20161102_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.clasedocumento'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Idp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.procedencia'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Idr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.remitente'),
        ),
    ]
